language: python
python:
  - "2.7"
install:
  - pip install -r test_requirements.txt --use-mirror
  - pip install flake8 --use-mirrors
  - pip install -q . --use-mirrors
before_script:
  - flake8 setup.py akanda
script: nosetests -d